apply-host-prod:
  extends: .apply-kong
  before_script:
    # Setup env
    - export KONG_HOST_DOMAIN=${WEB_DOMAIN_PROD}
    - export KONG_EP=${KONG_ENDPOINT_PROD}
    - export KONG_HOST_PROXY=${KONG_HOST_PROD}
  only:
    refs:
      - /^\d+.\d+.\d+-prod/
