.deploy-kube-dev:
  stage: deploy-dev
  when: manual
  #image: registryii.thaibevapp.com/tbdev/baseimage/alpine:latest
  image: ${HARBOR_REGISTRY}/docker_hub_proxy_cache/alpine:latest
  script:
    # Set environment variables
    - export STAGE=dev
    - export API_DOMAIN=${API_DOMAIN_DEV}
    - export VER_TAG=${COMMIT_ID}

    # Kubenetes
    - export KUBE_API_TOKEN=${KUBE_API_TOKEN_DEV}

    # Set kubectl
    - |
      apk add curl
      curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl \
          -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      cp kubectl /usr/local/bin/
    - |
      kubectl version --client;
      echo $KUBE_API_CERT | base64 -d > deploy.crt;
      kubectl config set-cluster k8s --server=https://$KUBE_API_EP --certificate-authority=deploy.crt --embed-certs=true;
      kubectl config set-credentials k8s_deployer --token=$KUBE_API_TOKEN;
    - |
      kubectl config set-context k8s --cluster k8s --user k8s_deployer --namespace=rtr-dev;

    - kubectl config use-context k8s

    # Install envsubst
    - apk add gettext

    # Clean up
    - kubectl get deploy --no-headers=true | grep "rtr-pms-${APP_NAME}-api-deployment-${STAGE}" | awk '{print $1}' | xargs kubectl delete deploy --ignore-not-found || true

    # Apply deployment
    - cat deployments/deployment.yml | envsubst | kubectl apply -f -

  only:
    refs:
      - master
      - /^dev-\d+\.\d+\.\d+$/
     #- /^\d+\.\d+\.\d+$/

.cronjob-kube-dev:
  stage: deploy-dev
  when: manual
  #image: registryii.thaibevapp.com/tbdev/baseimage/alpine:latest
  image: ${HARBOR_REGISTRY}/docker_hub_proxy_cache/alpine:latest
  script:
    # Set environment variables
    - export STAGE=dev
    - export API_DOMAIN=${API_DOMAIN_DEV}
    - export VER_TAG=${COMMIT_ID}

    # Kubenetes
    - export KUBE_API_TOKEN=${KUBE_API_TOKEN_DEV}

    # Set kubectl
    - |
      apk add curl
      curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl \
          -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      cp kubectl /usr/local/bin/
    - |
      kubectl version --client;
      echo $KUBE_API_CERT | base64 -d > deploy.crt;
      kubectl config set-cluster k8s --server=https://$KUBE_API_EP --certificate-authority=deploy.crt --embed-certs=true;
      kubectl config set-credentials k8s_deployer --token=$KUBE_API_TOKEN;
    - |
      kubectl config set-context k8s --cluster k8s --user k8s_deployer --namespace=rtr-dev;

    - kubectl config use-context k8s

    # Install envsubst
    - apk add gettext

    # Clean up
    - kubectl get cronjobs --no-headers=true | grep "rtr-pms-${APP_NAME}-cron-deployment-${STAGE}" | awk '{print $1}' | xargs kubectl delete cronjobs --ignore-not-found || true

    # Apply deployment
    - cat deployments/cronjob.yml | envsubst | kubectl apply -f -

  only:
    refs:
      - master
      - /^dev-\d+\.\d+\.\d+$/
     #- /^\d+\.\d+\.\d+$/

include:
  - local: /.gitlab-ci/deploy-dev/jobrecalculate.deploy.yml
  - local: /.gitlab-ci/deploy-dev/jobscheduledreport.deploy.yml
  - local: /.gitlab-ci/deploy-dev/jobsendemaillaunchform.deploy.yml
  - local: /.gitlab-ci/deploy-dev/jobrouteforms.deploy.yml
  - local: /.gitlab-ci/deploy-dev/jobsyncemployee.deploy.yml
  - local: /.gitlab-ci/deploy-dev/pms.deploy.yml
  - local: /.gitlab-ci/deploy-dev/reportassessmentstatustracking.deploy.yml
  - local: /.gitlab-ci/deploy-dev/reportpmscore.deploy.yml
  - local: /.gitlab-ci/deploy-dev/reportpmscoredetail.deploy.yml
  - local: /.gitlab-ci/deploy-dev/reportglobalvaluescoredetail.deploy.yml
  - local: /.gitlab-ci/deploy-dev/reportemployee.deploy.yml
  - local: /.gitlab-ci/deploy-dev/reportemployeekpi.deploy.yml
  - local: /.gitlab-ci/deploy-dev/reportgoalstatustracking.deploy.yml
  - local: /.gitlab-ci/deploy-dev/reportpmscoredetailall.deploy.yml
  - local: /.gitlab-ci/deploy-dev/reportfinalscore.deploy.yml
  - local: /.gitlab-ci/deploy-dev/reportdashboard.deploy.yml
  - local: /.gitlab-ci/deploy-dev/reportarchived.deploy.yml
