jobrouteforms-dev-deploy:
  extends: .cronjob-kube-dev
  before_script:
    # Overwrite this value globally.
    - APP_NAME=jobrouteforms

    # Export them for all jobs.
    - export APP_NAME

    - export MIN_REPLICAS=1
    - export MAX_REPLICAS=1
    - export CPU_LIMIT="300m"
    - export MEMORY_LIMIT="512Mi"
    - export JOB_DURATION="*/5 * * * *"
  only:
    changes:
      - .gitlab-ci/build/build-dev.yml
      - .gitlab-ci/build/jobrouteforms.build.yml
      - .gitlab-ci/deploy-dev/deploy-dev.yml
      - .gitlab-ci/deploy-dev/jobrouteforms.deploy.yml
      - api/**/*.go
      - cmd/jobrouteforms/*.go
      - build/develop/Dockerfile
      - config/**/*
      - deployments/cronjob.yml
      - docs/**/*
      - pkg/**/*.go
      - vendor/**/*
