pms-prod-deploy:
  stage: deploy-prod
  extends: .deploy-kube-prod
  before_script:
    # Overwrite this value globally.
    - APP_NAME=pms

    # Export them for all jobs.
    - export APP_NAME

    - export MIN_REPLICAS=3
    - export MAX_REPLICAS=9
    - export CPU_LIMIT="300m"
    - export MEMORY_LIMIT="512Mi"
    - export APP_BASE_PATH=/
