reportemployee-uat-deploy:
  stage: deploy-uat
  extends: .deploy-kube-uat
  before_script:
    # Overwrite this value globally.
    - APP_NAME=reportemployee

    # Export them for all jobs.
    - export APP_NAME

    - export MIN_REPLICAS=1
    - export MAX_REPLICAS=1
    - export CPU_LIMIT="1500m"
    - export MEMORY_LIMIT="1536Mi"
    - export APP_BASE_PATH=/reporting/employees
